# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-10 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_auto_20180308_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissiongroup',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='code',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='permission_group',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(max_length=32),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='PermissionGroup',
        ),
    ]
